### Create article
POST localhost:8080/api/v1/article
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDczMzYsImlkIjoxMSwicm9sZSI6IkFETUlOIiwiZXhwIjoxNjgyODMzNzM2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.C3JtZ3qZrnb44DeO-t41RPNbdNRZlUlikyrH0vdmje4f5-K6xgRZyXdng9ukhAOPATbe8KmovcAPV2Tfw8etsQ
Content-Type:  application/json

{
  "nameUZ": "uz",
  "nameRU": "ttt",
  "nameEN": "yyyy"
}


### Update article
PUT localhost:8080/api/v1/article/update/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDczMzYsImlkIjoxMSwicm9sZSI6IkFETUlOIiwiZXhwIjoxNjgyODMzNzM2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.C3JtZ3qZrnb44DeO-t41RPNbdNRZlUlikyrH0vdmje4f5-K6xgRZyXdng9ukhAOPATbe8KmovcAPV2Tfw8etsQ
Content-Type:  application/json

{
  "nameUZ": "eeee",
  "nameRU": "eeee",
  "nameEN": "eeee"
}

### Delete article
DELETE localhost:8080/api/v1/article/delete/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDczMzYsImlkIjoxMSwicm9sZSI6IkFETUlOIiwiZXhwIjoxNjgyODMzNzM2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.C3JtZ3qZrnb44DeO-t41RPNbdNRZlUlikyrH0vdmje4f5-K6xgRZyXdng9ukhAOPATbe8KmovcAPV2Tfw8etsQ
Content-Type:  application/json


### List article
GET localhost:8080/api/v1/article/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODI3NDczMzYsImlkIjoxMSwicm9sZSI6IkFETUlOIiwiZXhwIjoxNjgyODMzNzM2LCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.C3JtZ3qZrnb44DeO-t41RPNbdNRZlUlikyrH0vdmje4f5-K6xgRZyXdng9ukhAOPATbe8KmovcAPV2Tfw8etsQ
Content-Type:  application/json


