### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

//{
// "email": "ravshan@.com",
//  "password": "000"
//}


{
  "email": "www@gmail.com",
  "password": "0000"
}

### Registration
POST localhost:8080/api/v1/auth/registration
Content-Type:  application/json

{
  "name": "sss",
  "surname": "sss",
  "email": "ss@gmail.com",
  "phone": "222",
  "password": "222",
  "role": "MODERATOR"
}

