### Login
POST localhost:8080/api/v1/auth
Content-Type:  application/json

{
  "email": "asl@gmail.com",
  "password": "123123"
}

### REgistration
POST localhost:8080/api/v1/auth/registration
Content-Type:  application/json

{
  "name": "sss",
  "surname": "sss",
  "email": "ss@gmail.com",
  "phone": "222",
  "password": "222",
  "role": "MODERATOR"
}

