### Create article
POST localhost:8080/api/v1/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODIzNDI1OTMsImlkIjoxMSwicm9sZSI6IkFETUlOIiwiZXhwIjoxNjgyNDI4OTkzLCJpc3MiOiJLdW51eiB0ZXN0IHBvcnRhbGkifQ.cWmI1YUZPMT3ksGTXYMjGAthvZmfP2VBwmIq7o38c_RbR-uFMM0sUIUAtEWJiE7bz1C-oivpzLEN2Z0TxhxOJw
Content-Type:  application/json

{
  "nameUZ": "aaa",
  "nameRU": "aaa",
  "nameEN": "aaa"
}


### Update article
PUT localhost:8080/api/v1/category
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5ODY3MjksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNzMxMjksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.GCcqfVMZXrQMn4b3ZYedmAPaRWEYlKwlotM9HpCXmo0zYfSyn9brBLDCxDs6dL5OTw2HrExFOYb4XyQ-3IoDcg
Content-Type:  application/json

{
  "nameUZ": "eeee",
  "nameRU": "eeee",
  "nameEN": "eeee"
}

### Delete article
DELETE localhost:8080/api/v1/category/delete/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5ODY3MjksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNzMxMjksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.GCcqfVMZXrQMn4b3ZYedmAPaRWEYlKwlotM9HpCXmo0zYfSyn9brBLDCxDs6dL5OTw2HrExFOYb4XyQ-3IoDcg
Content-Type:  application/json


### List article
GET localhost:8080/api/v1/category/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5ODY3MjksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNzMxMjksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.GCcqfVMZXrQMn4b3ZYedmAPaRWEYlKwlotM9HpCXmo0zYfSyn9brBLDCxDs6dL5OTw2HrExFOYb4XyQ-3IoDcg
Content-Type:  application/json
