### Create article
POST localhost:8080/api/v1/region
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5ODY3MjksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNzMxMjksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.GCcqfVMZXrQMn4b3ZYedmAPaRWEYlKwlotM9HpCXmo0zYfSyn9brBLDCxDs6dL5OTw2HrExFOYb4XyQ-3IoDcg
Content-Type:  application/json

{
  "nameUZ": "qqq",
  "nameRU": "ttt",
  "nameEN": "yyyy"
}


### Update article
PUT localhost:8080/api/v1/region
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5ODY3MjksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNzMxMjksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.GCcqfVMZXrQMn4b3ZYedmAPaRWEYlKwlotM9HpCXmo0zYfSyn9brBLDCxDs6dL5OTw2HrExFOYb4XyQ-3IoDcg
Content-Type:  application/json

{
  "nameUZ": "eeee",
  "nameRU": "eeee",
  "nameEN": "eeee"
}

### Delete article
DELETE localhost:8080/api/v1/region/delete/3
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5ODY3MjksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNzMxMjksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.GCcqfVMZXrQMn4b3ZYedmAPaRWEYlKwlotM9HpCXmo0zYfSyn9brBLDCxDs6dL5OTw2HrExFOYb4XyQ-3IoDcg
Content-Type:  application/json


### List article
GET localhost:8080/api/v1/region/list
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE2ODE5ODY3MjksImlkIjoyLCJyb2xlIjoiQURNSU4iLCJleHAiOjE2ODIwNzMxMjksImlzcyI6Ikt1bnV6IHRlc3QgcG9ydGFsaSJ9.GCcqfVMZXrQMn4b3ZYedmAPaRWEYlKwlotM9HpCXmo0zYfSyn9brBLDCxDs6dL5OTw2HrExFOYb4XyQ-3IoDcg
Content-Type:  application/json

